### PR TITLE
Add config options for other features

### PR DESCRIPTION
**Pull request by Sdyess**
fix https://github.com/azerothcore/mod-money-for-kills/issues/2 #8 #9 #4

### CODE REVIEW

**Comment by Sdyess** [comment]
@BarbzYHOOL 

I may have found the issue with the suicide messages for you, but maybe only if you had suicide announce disabled. Was still broken so I fixed that I believe.

As for the double messages, I went through the original script and found the correct way things should work more or less or what their intentions were. Both loot and bounty should show, however I changed the condition slightly and fixed the string it displays, as they should be two different values rewarded to the player.

Test when you have time, I have the entire week off. Or someone else.

**Comment by BarbzYHOOL** [comment]
Why is the Pull Request 4 missing? it went from 3 to 5, that's curious.

Ok I tested and it no longer displays message on suicide.
However when I kill a player, it says "you loot X silver" + "You receive a bounty"
So the loot = take money from the player, and the bounty = extra gold for the kill, right?

So it's better now but I decided to test more in depth (seems like no one ever thought about testing properly this module).

I found these concerning issues: #8 #9 #4  if you want to take a look (in another PR maybe? as you prefer anyway, result matters more)

**Comment by Sdyess** [comment]
Recent commits should close all open issues for the module, unless you find I still missed something or broke something while fixing it all.

**Comment by BarbzYHOOL** [comment]
Missing headers fixed, thank you :P
I will test other stuff soon

**Comment by BarbzYHOOL** [comment]
All the issues are solved.
The "met an untimely demise" msg is so cringy lol

New bug: when I kill someone, my group friend doesn't get the bounty (near or far away)

(Note for all my tests I reload the conf with .reload conf)

**Comment by BarbzYHOOL** [comment]
@Sdyess I can't merge it because now there is a new bug, I should have merged it before the new commits but when I decided to do it you already pushed xD

So now there is still that bug with the option  MFK.Bounty.MoneyForNothing.

If I'm in a group and I kill a player, the other group members don't get the bounty for the kill.

**Comment by Sdyess** [comment]
@BarbzYHOOL 

It looks like that feature never existed in this module. Shared looting only applied to creature bounties apparently.

**Comment by BarbzYHOOL** [comment]
But when it showed the message, it was just a visual bug then? @Sdyess

**Comment by Sdyess** [comment]
I’m not sure. The original module awarded both a bounty and a pvp kill reward for killing a player. Neither of which were ever being shared with party members.

**Comment by BarbzYHOOL** [comment]
Alright hmm ok so I merge this since it's not a bug but rather a new small feature. Right?

**Comment by milestorme** [comment]
this works well AC>AzerothCore rev. 3f4c2f765220+ 2019-06-06 20:16:28 +0000 (master branch) (Unix, Release)

**Comment by BarbzYHOOL** [comment]
@Sdyess thank you for the PR!!

@milestorme thank you for testing

**Pull request merged**
